### ISSUE TITLE
Getting Unexpected response code 502

### ISSUE THREAD

**Issue by dgaurav-163** [hypertrack/live-app-android#16]
Hi HyperTrack Team

I am getting unexpected response code : 502 

Requested Url : https://api.hypertrack.com/api/v1/users/
Body : UserParams{deviceName='SM-G925I', name='gaurav', phone='null', lookupId='dsgdvgdgsffdtsftfst', photo='null', groupId='null', groupLookupId='null'}

Response : 502: There was an error on the server and we have been notified. Try again later. <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
Please suggest, in which scenario this error will occur

Thansks
Gaurav

**Comment by tulushev** [comment]
Updated to the new version
