### ISSUE TITLE
map is not Showing

### ISSUE THREAD

**Issue by ankurkthakur** [hypertrack/live-app-android#17]
![whatsapp image 2018-04-12 at 12 53 38 am](https://user-images.githubusercontent.com/35791735/38638915-5a405e4c-3ded-11e8-8228-83e60b74a821.jpeg)
 please help me out 

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="GoogleMapsKey">AIzaSyCO7_e6qLRHE9FWrg3FEAfy4pmGmbrr8_ec</string>
    <string name="branch_live">BRANCH_LIVE_KEY</string>
    <string name="branch_test">BRANCH_TEST_KEY</string>
</resources>

**Comment by tulushev** [comment]
Updated to the new version
