### ISSUE TITLE
Problem with Persistent notification

### ISSUE THREAD

**Issue by kajol-rajput** [hypertrack/live-app-android#19]
Hi Team, 
I have added Hypertrack sdk in my application. But i am facing an issue with persistent notifications while live location is shared. I am not able to set launch mode for the activity class which should be opened when this notification is tapped.
In ServiceNotificationParamsBuilder we can only set activity class name (setContentIntentActivityClass()) and extra data with intent (setContentIntentExtras()). Is there any method to set launch modes for intent?

Please help.

Thanks,
kajol

**Comment by tulushev** [comment]
Updated to the new version
