### ISSUE TITLE
SubscriptionUpdatesRcvr: onFailure: for deviceId

### ISSUE THREAD

**Issue by saravanan72** [hypertrack/live-app-android#26]
I m getting error  when  am going to get moment status by passing device id as an argument.

 final String deviceID = HyperTrack.getDeviceId(); // o/p 892BC97E-E7B3-4869-AW1A-EVE86A709AE3

hypertrackView = HyperTrackViews.getInstance(LocationTrackActivity.this, HyperTrackPublicKey);
hypertrackView.getDeviceMovementStatus(deviceID,
                new Consumer<MovementStatus>() {
                    @Override
                    public void accept(MovementStatus movementStatus) {
                        
                    }
                }
        );

hypertrackView.subscribeToDeviceUpdates(deviceID, new DeviceUpdatesHandler() {
            @Override
            public void onLocationUpdateReceived(@NonNull Location location) {
                Log.d(TAG, "onLocationUpdateReceived: " + location);
            }
            @Override
            public void onBatteryStateUpdateReceived(@MovementStatus.BatteryState int i) {
                Log.d(TAG, "onBatteryStateUpdateReceived: " + i);
            }

            @Override
            public void onStatusUpdateReceived(@NonNull StatusUpdate statusUpdate) {
                Log.d(TAG, "onStatusUpdateReceived: " + statusUpdate);
            }

            @Override
            public void onTripUpdateReceived(@NonNull Trip trip) {
                Log.d(TAG, "onTripUpdateReceived: " + trip);
            }

            @Override
            public void onError(Exception e, String deviceId) {
                Log.w(TAG, deviceId+" :onError: "+e.toString());
            }

            @Override
            public void onCompleted(String deviceId) {
                Log.d(TAG, "onCompleted: " + deviceId);
            }
        });

 I am getting error like below.

SubscriptionUpdatesRcvr: onFailure: for deviceId 892BC97E-E7B3-4869-AW1A-EVE86A709AE3
    com.apollographql.apollo.exception.ApolloException: Failed to parse subscription response: {data=null, errors=[{path=null, locations=[{line=1, column=877, sourceName=null}], message=Validation error of type FieldUndefined: Field 'generate_estimate' in type 'Destination' is undefined @ 'subscribeToLatestEvent/trip/destination/generate_estimate'}]}
        at com.apollographql.apollo.internal.interceptor.AppSyncSubscriptionInterceptor$1$1.run(AppSyncSubscriptionInterceptor.java:105)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at com.apollographql.apollo.internal.interceptor.AppSyncSubscriptionInterceptor$1$1.run(AppSyncSubscriptionInterceptor.java:79)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by deniszpua** [comment]
@saravannan72 thanks for reporting that. We're planning update, that will fix the issue early next week.

**Comment by saravanan72** [comment]
thanks for the kind reply.

**Comment by saravanan72** [comment]
get version update from com.hypertrack:hypertrack:3.4.3 to com.hypertrack:hypertrack:3.4.5 for com.hypertrack:hypertrack and com.hypertrack:hypertrack-views:0.2.0 to com.hypertrack:hypertrack-views:0.3.2 via slack group support. Now its working fine.
