### ISSUE TITLE
playstore link is broken

### ISSUE THREAD

**Issue by JerryGoyal** [hypertrack/live-app-android#33]
mentioned playstore link in description is broken https://play.google.com/store/apps/details?id=com.hypertrack.live

**Comment by alexhypertrack** [comment]
Hello @JerryGoyal : thank you for posting this. We have updated the link to change to the APK download as we are awaiting for Google Play Store approval. Please try https://github.com/hypertrack/live-app-android/releases/download/v3.6.4/app-release.apk to experience HyperTrack Live on Android.
