### ISSUE TITLE
Live app notification though its not tracking

### ISSUE THREAD

**Issue by Bharath-pg** [hypertrack/live-app-android#35]
I have cleared live app in recent apps and also I made sure in playground that device is not tracking. But still if I turn on gps I get to see notification saying searching for location. Hopw you'll fix this. 
Attached necessary screenhots
![Screenshot_2020-09-01-15-25-46-198_com miui home](https://user-images.githubusercontent.com/43911332/91835916-ae671800-ec67-11ea-9189-0cd2a7b1ceb3.jpg)
![Screenshot_2020-09-01-15-25-57-962_com hypertrack live](https://user-images.githubusercontent.com/43911332/91835923-b030db80-ec67-11ea-85bd-80df7b5fda06.jpg)

**Comment by deniszpua** [comment]
```
{
    "app-name": "com.hypertrack.live",
    "app-version-string": "3.8.1",
    "app-version-number": 4005003,
    "device-hardware": "qcom",
    "device-brand": "Xiaomi",
    "device-model": "Redmi Note 7 Pro",
    "name": "Bharath",
    "network-operator": "AIRTEL",
    "os-hardware-identifier": "08fc4150cccca37f",
    "os-name": "Android",
    "os-version": "9",
    "sdk-version": "4.5.3",
    "play-services-version": "203314028",
}
```
